### ISSUE TITLE
Unexpected Table Item Padding in PyQt6

### ISSUE THREAD

**Issue by Alexhuszagh** [Alexhuszagh/BreezeStyleSheets#31]
### Issue

Using PyQt6, the table items/headers have unexpected padding under the elements, which means with the default item sizes they are practically illegible. This differs friom both the native theme and PyQt5.

**PyQt6 Dark**

![Padding Dark](https://user-images.githubusercontent.com/9440903/165584876-d412d818-4a36-4493-9503-8b1fee2df5d2.png)

**PyQt5 Dark**

![Padding Dark Qt5](https://user-images.githubusercontent.com/9440903/165584863-94d28c01-f5cf-4fe5-b02b-bf7f83ce737e.png)

**PyQt6 Native**

![Padding Native](https://user-images.githubusercontent.com/9440903/165584887-0bdb858b-f53a-4955-af4e-9a4b044f79cf.png)

**Comment by Alexhuszagh** [comment]
The offending QSS seems to be, which controls the arrow positions in the QHeaderView. It also causes the left overlap in the QHeaderView column header for the 2nd column.

```css
QHeaderView::down-arrow
{
    image: url(^style^down_arrow.svg);
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-top: 0.2em;
    width: 0.8em;
    height: 0.5em;
}

QHeaderView::up-arrow
{
    image: url(^style^up_arrow.svg);
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-top: 0.2em;
    width: 0.8em;
    height: 0.5em;
}
```
