### ISSUE TITLE
Standard Icons are not Overwritten

### ISSUE THREAD

**Issue by Alexhuszagh** [Alexhuszagh/BreezeStyleSheets#33]
### Issue

Standard icons are only being overwritten in `QDialogButtonBox` and `QMessageBox`, leading to ugly icons like the following:
![QMenu](https://user-images.githubusercontent.com/9440903/165794688-2c666468-d39e-461c-a16d-6003ffb357fa.png)

This is because the icons are only overwritten here:

```css
QDialogButtonBox
{
    dialogbuttonbox-buttons-have-icons: true;

    dialog-cancel-icon: url(^style^dialog_cancel.svg);
    dialog-close-icon: url(^style^dialog_close.svg);
    dialog-ok-icon: url(^style^dialog_ok.svg);
    dialog-open-icon: url(^style^dialog_open.svg);
    dialog-reset-icon: url(^style^dialog_reset.svg);
    dialog-save-icon: url(^style^dialog_save.svg);
    /**
     *  No support yet for overriding saveall.
     *  dialog-saveall-icon: url(^style^dialog_saveall.svg);
     */
    dialog-yes-icon: url(^style^dialog_ok.svg);
    dialog-help-icon: url(^style^dialog_help.svg);
    dialog-no-icon: url(^style^dialog_no.svg);
    dialog-apply-icon: url(^style^dialog_ok.svg);
    dialog-discard-icon: url(^style^dialog_discard.svg);
}

QMessageBox
{
    messagebox-critical-icon: url(^style^message_critical.svg);
    messagebox-information-icon: url(^style^message_information.svg);
    messagebox-question-icon: url(^style^message_question.svg);
    messagebox-warning-icon: url(^style^message_warning.svg);
}
```

### Solution

This might not be possible with stylesheets (it's unlikely), so I need to clearly document how to do this with actual code.
