### ISSUE TITLE
[QUESTION] Remove guidings from QTreeWidget

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#70]
## Question
Is there a way to hide the guidings from QTreeWidget, but still leave the arrows that expand/collapse items? In other words, leave them like in native Windows.

![guidings](https://user-images.githubusercontent.com/17036813/202721528-1b47e6b5-c0c7-4b99-82f1-e30e1110ed57.png)

**Comment by Alexhuszagh** [comment]
Yes, this would be doable by changing the `QTreeView:branch` styles yusing an [extension](https://github.com/Alexhuszagh/BreezeStyleSheets/tree/main/extension) for `border-image` [from](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/0bd11fbba29304a00795540b8bac67265dc83dec/template/stylesheet.qss.in#L1744-L1807) to:

```css
QTreeView::branch:has-siblings
{
    border-image: none;
    image: none;
}

/* These branch indicators don't scale */
QTreeView::branch:!has-siblings
{
    border-image: none;
    image: none;
}

QTreeView::branch:has-siblings:adjoins-item
{
    border-image: none;
}

QTreeView::branch:!has-children:!has-siblings:adjoins-item
{
    border-image: none;
}

QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings
{
    image: url(^style^branch_closed.svg);
}

QTreeView::branch:has-children:!has-siblings:closed:hover,
QTreeView::branch:closed:has-children:has-siblings:hover
{
    image: url(^style^branch_closed_hover.svg);
}

QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:open:has-children:!has-siblings
{
    border-image: none;
}

QTreeView::branch:closed:has-children:has-siblings,
QTreeView::branch:open:has-children:has-siblings
{
    border-image: none;
}

QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings
{
    image: url(^style^branch_open.svg);
}

QTreeView::branch:open:has-children:!has-siblings:hover,
QTreeView::branch:open:has-children:has-siblings:hover
{
    image: url(^style^branch_open_hover.svg);
}
```

Note I wouldn't do this by default, so I'd add an `objectName` and then have your widgets using said object name.

```css
QTreeView[objectName="nobranch"]::branch:has-siblings
{
    border-image: none;
    image: none;
}

/* These branch indicators don't scale */
QTreeView[objectName="nobranch"]::branch:!has-siblings
{
    border-image: none;
    image: none;
}

QTreeView[objectName="nobranch"]::branch:has-siblings:adjoins-item
{
    border-image: none;
}

QTreeView[objectName="nobranch"]::branch:!has-children:!has-siblings:adjoins-item
{
    border-image: none;
}

QTreeView[objectName="nobranch"]::branch:has-children:!has-siblings:closed,
QTreeView[objectName="nobranch"]::branch:closed:has-children:has-siblings
{
    image: url(^style^branch_closed.svg);
}

QTreeView[objectName="nobranch"]::branch:has-children:!has-siblings:closed:hover,
QTreeView[objectName="nobranch"]::branch:closed:has-children:has-siblings:hover
{
    image: url(^style^branch_closed_hover.svg);
}

QTreeView[objectName="nobranch"]::branch:has-children:!has-siblings:closed,
QTreeView[objectName="nobranch"]::branch:open:has-children:!has-siblings
{
    border-image: none;
}

QTreeView[objectName="nobranch"]::branch:closed:has-children:has-siblings,
QTreeView[objectName="nobranch"]::branch:open:has-children:has-siblings
{
    border-image: none;
}

QTreeView[objectName="nobranch"]::branch:open:has-children:!has-siblings,
QTreeView[objectName="nobranch"]::branch:open:has-children:has-siblings
{
    image: url(^style^branch_open.svg);
}

QTreeView[objectName="nobranch"]::branch:open:has-children:!has-siblings:hover,
QTreeView[objectName="nobranch"]::branch:open:has-children:has-siblings:hover
{
    image: url(^style^branch_open_hover.svg);
}
```
